name: 'deploy'
on:
    push:
      branches:
        - master
jobs:
    site-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src